export const fullMenuData: Record<string, any[]> = {
  soups: [
    { name: 'Tomato Soup (Only Tomato)', img: 'https://loremflickr.com/600/400/tomato,soup,food/all?lock=9407', desc: 'A rich and smooth classic tomato soup made from fresh tomatoes and herbs.', price: '$4.99', spice: 0, tags: ['vegan'] },
    { name: 'Sweet Corn Soup', img: 'https://loremflickr.com/600/400/corn,soup,food/all?lock=5210', desc: 'A comforting creamy soup made with sweet corn and delicate flavors. (Veg, Chicken, Egg, Shrimp)', price: '$4.99', spice: 0, tags: [] },
    { name: 'Hot And Sour Soup', img: 'https://loremflickr.com/600/400/spicy,soup,food/all?lock=6262', desc: 'A bold blend of spicy and tangy flavors with fresh vegetables and aromatic seasonings. (Veg, Chicken, Egg, Shrimp)', price: '$4.99', spice: 2, tags: ['spicy'] },
    { name: 'Manchow Soup', img: 'https://loremflickr.com/600/400/noodle,soup,food/all?lock=8395', desc: 'A spicy and flavorful Indo-Chinese soup topped with crispy noodles. (Veg, Chicken, Egg, Shrimp)', price: '$4.99', spice: 2, tags: ['spicy'] },
  ],
  vegAppetizers: [
    { name: 'Veg Samosa (2 pcs)', img: 'https://loremflickr.com/600/400/samosa,food/all?lock=5065', desc: 'Crispy pastries filled with a spiced mixture of vegetables and potatoes.', price: '$5.99', spice: 1, tags: ['vegan', 'bestseller'] },
    { name: 'Veg Spring Rolls (5 pcs)', img: 'https://loremflickr.com/600/400/springrolls,food/all?lock=3934', desc: 'Crispy, golden-brown rolls packed with a flavorful blend of fresh vegetables.', price: '$5.99', spice: 0, tags: ['vegan'] },
    { name: 'Veg Pakoda', img: 'https://loremflickr.com/600/400/pakora,fritters,food/all?lock=7404', desc: 'Crispy and golden fritters made with mixed vegetables, gram flour, and aromatic spices, perfect for a delightful snack or appetizer.', price: '$7.99', spice: 1, tags: ['vegan'] },
    { name: 'Crispy Potato Wedges', img: 'https://loremflickr.com/600/400/potato,wedges,food/all?lock=5261', desc: 'Golden and crispy potato wedges seasoned with herbs and spices.', price: '$4.99', spice: 1, tags: ['vegan'] },
    { name: 'Mozzarella Cheese Sticks', img: 'https://loremflickr.com/600/400/mozzarella,sticks,food/all?lock=1348', desc: 'Golden, crispy sticks of melted mozzarella cheese, perfect for dipping in marinara sauce.', price: '$5.99', spice: 0, tags: [] },
    { name: 'Gobi Manchurian', img: 'https://loremflickr.com/600/400/cauliflower,fry,food/all?lock=1085', desc: 'Crispy cauliflower tossed in a spicy Indo-Chinese sauce.', price: '$12.99', spice: 2, tags: ['spicy', 'vegan'] },
  ],
  nonVegAppetizers: [
    { name: 'Chicken 65 Boneless', img: 'https://loremflickr.com/600/400/fried,chicken,food/all?lock=8122', desc: 'Spicy chicken chunks deep-fried with authentic flavors.', price: '$12.99', spice: 2, tags: ['spicy', 'bestseller'] },
    { name: 'Chilli Chicken', img: 'https://loremflickr.com/600/400/chilli,chicken,food/all?lock=8358', desc: 'Classic Indo-Chinese chicken with spicy chili sauce.', price: '$12.99', spice: 3, tags: ['spicy'] },
    { name: 'Chicken Manchurian', img: 'https://loremflickr.com/600/400/vegetable,curry,food/all?lock=3590', desc: 'Crispy chicken tossed in a signature Manchurian sauce.', price: '$12.99', spice: 2, tags: [] },
    { name: 'Drunk\'n Fish', img: 'https://loremflickr.com/600/400/chickpea,curry,food/all?lock=8314', desc: 'A Fish marinated with house seasoning and Coated with Crispy beer batter.', price: '$16.99', spice: 1, tags: ['new'] },
    { name: 'Kurkuree Momos', img: 'https://loremflickr.com/600/400/fried,dumplings,food/all?lock=2170', desc: 'Crispy chicken-filled momos with bold spices and a crunchy bite.', price: '$12.99', spice: 2, tags: [] },
    { name: 'Masala Momos', img: 'https://loremflickr.com/600/400/spicy,dumplings,food/all?lock=9471', desc: 'Chicken-filled momos tossed in rich Indian masala for a bold and spicy street-style flavor', price: '$12.99', spice: 2, tags: ['spicy'] },
  ],
  vegEntree: [
    { name: 'Dhal Makhani', img: 'https://loremflickr.com/600/400/dal,makhani,food/all?lock=7030', desc: 'A rich and creamy lentil dish made with black lentils, butter, and cream, slow-cooked with spices.', price: '$12.99', spice: 0, tags: ['bestseller'] },
    { name: 'Veg Korma', img: 'https://loremflickr.com/600/400/vegetable,curry,food/all?lock=3590', desc: 'Mixed vegetables simmered in a flavorful, coconut-based creamy sauce.', price: '$12.99', spice: 1, tags: ['vegan'] },
    { name: 'Saag Paneer', img: 'https://loremflickr.com/600/400/palak,paneer,food/all?lock=3527', desc: 'Creamy spinach curry with tender cubes of paneer, spiced to perfection.', price: '$13.99', spice: 1, tags: ['bestseller'] },
    { name: 'Paneer Butter Masala', img: 'https://loremflickr.com/600/400/chickpea,curry,food/all?lock=8314', desc: 'Rich and mildly spiced tomato-based curry with soft paneer cubes and a touch of cream.', price: '$13.99', spice: 1, tags: ['chef'] },
    { name: 'Paneer Tikka Masala', img: 'https://loremflickr.com/600/400/paneer,tikka,food/all?lock=2141', desc: 'Grilled paneer pieces cooked in a spiced, flavorful tomato-based gravy.', price: '$13.99', spice: 1, tags: [] },
    { name: 'Kadai Paneer', img: 'https://loremflickr.com/600/400/chickpea,curry,food/all?lock=8314', desc: 'Paneer cooked with bell peppers, onions, and spices in a traditional kadai-style gravy.', price: '$13.99', spice: 2, tags: [] },
    { name: 'Channa Masala', img: 'https://loremflickr.com/600/400/chickpea,curry,food/all?lock=8314', desc: 'Chickpeas simmered in a tangy, spiced tomato-onion sauce, packed with bold North Indian flavors.', price: '$12.99', spice: 1, tags: ['vegan'] },
    { name: 'Aloo Gobi', img: 'https://loremflickr.com/600/400/aloo,gobi,food/all?lock=4891', desc: 'Potatoes and cauliflower cooked with aromatic herbs and Indian spices.', price: '$12.99', spice: 1, tags: ['vegan'] },
  ],
  nonVegEntree: [
    { name: 'Curry Express Special Chicken Curry', img: 'https://loremflickr.com/600/400/indian,chicken,curry,food/all?lock=4637', desc: 'A flavorful chicken curry cooked with Indian spices for a rich and aromatic taste.', price: '$14.99', spice: 2, tags: ['chef', 'bestseller'] },
    { name: 'Murg Saagwala', img: 'https://loremflickr.com/600/400/spinach,chicken,curry,food/all?lock=7768', desc: 'Tender chicken pieces cooked with fresh spinach leaves and a blend of traditional spices.', price: '$14.99', spice: 1, tags: [] },
    { name: 'Kadai Chicken', img: 'https://loremflickr.com/600/400/chickpea,curry,food/all?lock=8314', desc: 'Grilled chicken pieces marinated in aromatic spices.', price: '$14.99', spice: 2, tags: [] },
    { name: 'Butter Chicken', img: 'https://loremflickr.com/600/400/butter,chicken,food/all?lock=3240', desc: 'Juicy chicken simmered in a creamy tomato-based gravy enriched with butter and mild spices.', price: '$14.99', spice: 1, tags: ['bestseller'] },
    { name: 'Chicken Tikka Masala', img: 'https://loremflickr.com/600/400/chicken,tikka,masala,food/all?lock=2002', desc: 'Grilled chicken pieces cooked with onions in a spiced tomato and cream-based curry.', price: '$14.99', spice: 1, tags: ['chef'] },
    { name: 'Chicken Vindaloo', img: 'https://loremflickr.com/600/400/spicy,chicken,curry,food/all?lock=8270', desc: 'Spicy and tangy Goan-style chicken curry made with vinegar, garlic, potatoes, and Indian spices.', price: '$14.99', spice: 3, tags: ['spicy'] },
    { name: 'Chicken Korma', img: 'https://loremflickr.com/600/400/chicken,korma,food/all?lock=4694', desc: 'Creamy and mildly spiced chicken curry cooked in a coconut-based sauce for a rich, indulgent taste.', price: '$14.99', spice: 1, tags: [] },
    { name: 'Madras Chicken', img: 'https://loremflickr.com/600/400/chickpea,curry,food/all?lock=8314', desc: 'A spicy and tangy chicken curry with bold South Indian flavors and a rich coconut-tomato base.', price: '$14.99', spice: 2, tags: [] },
    { name: 'Chicken Chettinadu', img: 'https://loremflickr.com/600/400/chickpea,curry,food/all?lock=8314', desc: 'A fiery South Indian specialty with tender chicken cooked in a blend of roasted spices, coconut, and curry leaves.', price: '$14.99', spice: 3, tags: ['spicy'] },
  ],
  seaFoodCurry: [
    { name: 'Goan Fish Curry', img: 'https://loremflickr.com/600/400/fish,curry,food/all?lock=971', desc: 'Fresh fish simmered in a tangy coconut milk sauce, flavored with tamarind and aromatic spices.', price: '$15.99', spice: 2, tags: ['chef'] },
    { name: 'Coastal Fish Curry', img: 'https://loremflickr.com/600/400/fish,curry,bowl,food/all?lock=2056', desc: 'Fresh fish cooked in a spiced coconut-based gravy, inspired by the bold flavors of coastal India.', price: '$15.99', spice: 2, tags: [] },
    { name: 'Shrimp Vindaloo', img: 'https://loremflickr.com/600/400/shrimp,curry,food/all?lock=6149', desc: 'Succulent shrimp marinated in vinegar, potatoes, and spices for a bold and flavorful dish.', price: '$16.99', spice: 3, tags: ['spicy'] },
    { name: 'Coastal Shrimp Curry', img: 'https://loremflickr.com/600/400/prawn,curry,food/all?lock=4189', desc: 'Rich and aromatic shrimp curry infused with spices and herbs typical of Indian coastal cuisine.', price: '$16.99', spice: 2, tags: [] },
  ],
  goatCurry: [
    { name: 'Goat Curry', img: 'https://loremflickr.com/600/400/mutton,curry,food/all?lock=27', desc: 'Tender goat meat blended with coastal spices, curry leaves, and aromatic herbs.', price: '$16.99', spice: 2, tags: ['bestseller'] },
    { name: 'Goat Korma', img: 'https://loremflickr.com/600/400/mutton,korma,food/all?lock=2700', desc: 'Creamy goat curry simmered in a coconut-based sauce, enhanced with aromatic spices.', price: '$16.99', spice: 1, tags: [] },
    { name: 'Kadai Goat', img: 'https://loremflickr.com/600/400/chickpea,curry,food/all?lock=8314', desc: 'Tender goat pieces cooked in a spicy masala with bell peppers, onions, and traditional spices.', price: '$16.99', spice: 2, tags: [] },
    { name: 'Goat Vindaloo', img: 'https://loremflickr.com/600/400/spicy,mutton,curry,food/all?lock=5067', desc: 'Fiery and tangy curry made with marinated goat meat, vinegar, potatoes, and a robust blend of spices.', price: '$16.99', spice: 3, tags: ['spicy'] },
    { name: 'Mutton Rogan Josh', img: 'https://loremflickr.com/600/400/rogan,josh,food/all?lock=6662', desc: 'Slow-cooked mutton in a fragrant, aromatic gravy with Kashmiri spices and a hint of yogurt.', price: '$16.99', spice: 2, tags: ['chef'] },
    { name: 'Goat Tikka Masala', img: 'https://loremflickr.com/600/400/mutton,curry,food/all?lock=8823', desc: 'Grilled goat tikka pieces simmered in a rich, spiced tomato-based gravy.', price: '$16.99', spice: 2, tags: [] },
    { name: 'Madras Goat', img: 'https://loremflickr.com/600/400/spicy,lamb,curry,food/all?lock=6724', desc: 'Spicy and tangy goat curry cooked with tamarind and traditional South Indian spices.', price: '$16.99', spice: 3, tags: ['spicy'] },
  ],
  burgerFusions: [
    { name: 'Half Pound Cheese Burger (B/C)', img: 'https://loremflickr.com/600/400/cheeseburger,food/all?lock=4877', desc: '2 grilled 4oz meat patty, Cheddar Cheese, Pickle, Lettuce, tomato, Onions, Garlic mayo.', price: '$12.99', spice: 0, tags: [] },
    { name: 'BBQ Cheese Burger (B/C)', img: 'https://loremflickr.com/600/400/bbq,burger,food/all?lock=7455', desc: 'Grilled Meat with BBQ Rab, BBQ Aoli, Cheddar cheese, Lettuce, tomato, Onions, Pickle.', price: '$12.99', spice: 0, tags: [] },
    { name: 'Curry Express Special (B/C)', img: 'https://loremflickr.com/600/400/gourmet,burger,food/all?lock=8103', desc: 'Choice of meat smash with house seasoning, Loaded Pepper jack cheese, Lettuce, tomato, Pickle, Onion, garlic Aioli.', price: '$12.99', spice: 1, tags: ['chef'] },
    { name: 'Crispy Chicken Sandwich', img: 'https://loremflickr.com/600/400/chicken,sandwich,food/all?lock=2143', desc: 'Crispy chicken chunks with house Seasoning, Lettuce, tomato, onion, garlic Aioli, cheddar Cheese.', price: '$12.99', spice: 1, tags: ['bestseller'] },
  ],
  breads: [
    { name: 'Garlic Naan', img: 'https://loremflickr.com/600/400/garlic,naan,food/all?lock=25', desc: 'Tandoor-baked naan topped with fresh garlic and butter for a flavorful twist.', price: '$3.00', spice: 0, tags: ['bestseller', 'vegan'] },
    { name: 'Butter Naan', img: 'https://loremflickr.com/600/400/butter,naan,food/all?lock=6379', desc: 'Soft, pillowy Indian flatbread cooked in a tandoor and generously brushed with melted butter for extra flavor.', price: '$2.50', spice: 0, tags: [] },
    { name: 'Malabar Paratha', img: 'https://loremflickr.com/600/400/parotta,food/all?lock=8122', desc: 'Soft and flaky layered South Indian flatbread cooked to golden perfection.', price: '$2.00', spice: 0, tags: [] },
  ],
  dumBiryani: [
    { name: 'Chicken Biryani', img: 'https://loremflickr.com/600/400/chicken,biryani,food/all?lock=2918', desc: 'Marinated chicken, fragrant basmati rice, and a blend of spices — slow-cooked to perfection.', price: '$14.99', spice: 2, tags: ['bestseller'] },
    { name: 'Chicken Gilma Biryani', img: 'https://loremflickr.com/600/400/spicy,biryani,food/all?lock=4724', desc: 'Chicken Gilma Biryani — tender chicken and fragrant rice cooked with rich Gilma spices for a bold, flavorful delight.', price: '$15.99', spice: 3, tags: ['spicy', 'chef'] },
    { name: 'Goat Biryani', img: 'https://loremflickr.com/600/400/mutton,biryani,food/all?lock=2496', desc: 'Tender goat meat, spiced basmati rice, aromatic herbs, and saffron for a rich flavor.', price: '$15.99', spice: 2, tags: ['chef'] },
    { name: 'Shrimp Biryani', img: 'https://loremflickr.com/600/400/prawn,biryani,food/all?lock=5350', desc: 'Succulent shrimp, basmati rice, and a special blend of spices cooked together.', price: '$15.99', spice: 2, tags: [] },
    { name: 'Egg Biryani', img: 'https://loremflickr.com/600/400/egg,biryani,food/all?lock=6274', desc: 'Boiled eggs layered with basmati rice and flavorful Indian spices.', price: '$12.99', spice: 1, tags: [] },
    { name: 'Veg Biryani', img: 'https://loremflickr.com/600/400/vegetable,biryani,food/all?lock=4332', desc: 'Aromatic rice dish with fresh vegetables and traditional Indian spices.', price: '$12.99', spice: 1, tags: ['vegan'] },
    { name: 'Paneer Biryani', img: 'https://loremflickr.com/600/400/paneer,biryani,food/all?lock=8409', desc: 'Soft paneer cubes cooked with fragrant basmati rice, herbs, and traditional Indian spices for a flavorful, vegetarian delight.', price: '$13.99', spice: 1, tags: [] },
  ],
  desserts: [
    { name: 'Rasamalai', img: 'https://loremflickr.com/600/400/rasmalai,food/all?lock=7026', desc: 'A creamy and flavorful Indian dessert made from soft cheese dumplings soaked in sweet, aromatic milk flavored with cardamom and garnished with nuts.', price: '$5.99', spice: 0, tags: ['chef'] },
    { name: 'Gulab Jamun', img: 'https://loremflickr.com/600/400/gulab,jamun,food/all?lock=4494', desc: 'A delightful Indian dessert made from soft, deep-fried dough balls soaked in a fragrant sugar syrup infused with rose water and cardamom — offering a sweet and indulgent treat.', price: '$5.99', spice: 0, tags: ['bestseller'] },
    { name: 'Rice Kheer', img: 'https://loremflickr.com/600/400/rice,pudding,food/all?lock=1010', desc: 'A traditional Indian rice pudding made with slow-cooked basmati rice, milk, sugar, and flavored with cardamom.', price: '$4.99', spice: 0, tags: [] },
  ],
  beverages: [
    { name: 'Strawberry Lassi', img: 'https://loremflickr.com/600/400/strawberry,smoothie,food/all?lock=8894', desc: 'A fruity twist on the classic lassi — blended with fresh strawberry flavor for a sweet and tangy taste.', price: '$4.99', spice: 0, tags: [] },
    { name: 'Mango Lassi', img: 'https://loremflickr.com/600/400/mango,lassi,food/all?lock=9026', desc: 'A delicious blend of yogurt and mango pulp — sweet, smooth, and perfect as a refreshing dessert drink.', price: '$4.99', spice: 0, tags: ['bestseller'] },
  ],
  indoChinese: [
    { name: 'Hakka Noodles (Veg, Chicken, Egg, Shrimp, Paneer, Mix)', img: 'https://loremflickr.com/600/400/hakka,noodles,food/all?lock=6510', desc: 'Stir-fried noodles tossed with fresh vegetables, sauces, and your choice of protein in classic Indo-Chinese style.', price: '$12.99', spice: 1, tags: ['bestseller'] },
    { name: 'Bombay Noodles (Veg, Chicken, Egg, Shrimp, Paneer, Mix)', img: 'https://loremflickr.com/600/400/spicy,noodles,food/all?lock=6597', desc: 'Flavor-packed noodles cooked with bold Indian spices, vegetables, and your choice of protein for a street-style twist.', price: '$12.99', spice: 2, tags: ['chef'] },
  ],
  kidsMenu: [
    { name: 'French Fries', img: 'https://loremflickr.com/600/400/french,fries,food/all?lock=5668', desc: 'Golden, crispy fries — a classic favorite that kids love to munch on!', price: '$3.99', spice: 0, tags: ['vegan'] },
    { name: 'Chicken Nuggets (5 pcs)', img: 'https://loremflickr.com/600/400/chicken,nuggets,food/all?lock=1282', desc: 'Tender, bite-sized chicken pieces, breaded and fried until crispy and delicious.', price: '$4.99', spice: 0, tags: [] },
    { name: 'Chicken Tenders', img: 'https://loremflickr.com/600/400/chicken,tenders,food/all?lock=8402', desc: 'Crispy golden chicken strips served hot and packed with flavor.', price: '$6.99', spice: 0, tags: [] },
    { name: 'Chicken Wings', img: 'https://loremflickr.com/600/400/chicken,wings,food/all?lock=9065', desc: 'Juicy chicken wings tossed and cooked to crispy perfection.', price: '$6.99', spice: 0, tags: [] },
    { name: 'Shrimp Nuggets', img: 'https://loremflickr.com/600/400/fried,shrimp,food/all?lock=6846', desc: 'Crispy fried shrimp seasoned with bold flavors for the perfect bite.', price: '$6.99', spice: 0, tags: [] },
  ],
  indoMexican: [
    { name: 'Chicken Over Rice', img: 'https://loremflickr.com/600/400/chicken,over,rice,food/all?lock=6640', desc: 'Spanish rice Top up with Buttery Chicken, Pico de gallo, Cheese, lettuce, Camin Sour Cream.', price: '$12.99', spice: 1, tags: ['chef'] },
    { name: 'Quesadilla', img: 'https://loremflickr.com/600/400/quesadilla,food/all?lock=1076', desc: 'House marinated Chicken, red Onion, black beans, Cilantro, pico de galo, Camin Sour Cream, Side of salsa.', price: '$6.99', spice: 1, tags: [] },
    { name: 'Burrito', img: 'https://loremflickr.com/600/400/burrito,food/all?lock=3328', desc: 'A large flour tortilla wrappe around a Savory filling, grilled chicken with house seasoning, beans, rice, Cheese, Lettuce and Salsa.', price: '$3.99', spice: 1, tags: ['bestseller'] },
    { name: 'Corn Dog', img: 'https://loremflickr.com/600/400/corn,dog,food/all?lock=2087', desc: 'A Sausage Coated in a thick, Sweet Cornmeal batter, Served with house mayo.', price: '$6.99', spice: 0, tags: [] },
    { name: 'Nachos', img: 'https://loremflickr.com/600/400/nachos,food/all?lock=2060', desc: 'A Corn tortilla chips, queso cheese Sauce, green Onions, pickled jalapenos, cumin sour cream grilled chicken with house seasoning', price: '$3.99', spice: 1, tags: [] },
  ],
};

export const categoryLabels: Record<string, string> = {
  all: 'All Dishes',
  soups: 'Soups',
  vegAppetizers: 'Veg Appetizers',
  nonVegAppetizers: 'Non-Veg Appetizers',
  vegEntree: 'Veg-Entree',
  nonVegEntree: 'Non Veg Entree',
  seaFoodCurry: 'Sea Food Curry',
  goatCurry: 'Goat Curry',
  burgerFusions: 'Burger Fusion\'s',
  breads: 'Breads',
  dumBiryani: 'Hyderabadi Dum Biryani',
  desserts: 'Desserts',
  beverages: 'Beverages',
  indoChinese: 'Indo-Chinese',
  kidsMenu: 'Kids Menu',
  indoMexican: 'Indo-Mexican and Indo-American'
};

export const categories = Object.keys(categoryLabels).map(key => ({
  id: key,
  label: categoryLabels[key]
}));
